# Shell variables
# Generated by 'wal'
wallpaper='/root/.config/wpg/wallpapers/happytrails.jpg'

# Special
background='#2c2c2c'
foreground='#bcfafe'
cursor='#bcfafe'

# Colors
color0='#2c2c2c'
color1='#d3d385'
color2='#fecf6b'
color3='#d3bb5b'
color4='#9dfeaf'
color5='#4299df'
color6='#fefe4a'
color7='#bcfafe'
color8='#95c1fe'
color9='#d3d385'
color10='#fecf6b'
color11='#d3bb5b'
color12='#9dfeaf'
color13='#4299df'
color14='#fefe4a'
color15='#bcfafe'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
